package com.terradatum.jdbc.db.objects.jdbcTest;

import com.terradatum.jdbc.JdbcArrayList;
import com.terradatum.jdbc.StructArrayList;

import java.lang.reflect.InvocationTargetException;
import java.sql.Array;
import java.sql.SQLException;
import java.util.ArrayList;

import static java.sql.Types.*;

/**
 * DO NOT MODIFY!!! This class was generated by the Terradatum JDBC Code Generator and will be overwritten if regenerated
 * @date 2016-05-01T17:05:21.584
 */
public class ChildTbl extends StructArrayList<ChildObj> {
  public static final String SQL_TYPE_NAME = "jdbc_test.child_tbl";
  public static final char EDB_ARRAY_DELIMITER = ',';
  private final ArrayList<ChildObj> delegate = new ArrayList<>();

  /**
   * Required default constructor.
   */
  @SuppressWarnings("unused")
  public ChildTbl() {}

  @Override
  protected ArrayList<ChildObj> delegate() {
    return delegate;
  }

  @Override
  public String getSQLTypeName() {
    return SQL_TYPE_NAME;
  }

  @Override
  public String getBaseTypeName() {
    return ChildObj.SQL_TYPE_NAME;
  }

  @Override
  public int getBaseType() {
    return STRUCT;
  }

  @Override
  public char getEdbArrayDelimiter() {
    return EDB_ARRAY_DELIMITER;
  }

  @Override
  public ChildTbl setArray(Array array) throws SQLException, InvocationTargetException,
      NoSuchMethodException, IllegalAccessException, NoSuchFieldException {
    super.setArray(array);
    return this;
  }

  @Override
  public ChildTbl setElements(ChildObj[] elements) throws SQLException {
    super.setElements(elements);
    return this;
  }
}