package com.terradatum.jdbc.db.objects.jdbcTest;

import com.terradatum.jdbc.JdbcArrayList;
import com.terradatum.jdbc.StructArrayList;

import java.lang.reflect.InvocationTargetException;
import java.sql.Array;
import java.sql.SQLException;
import java.util.ArrayList;

import static java.sql.Types.*;

/**
 * DO NOT MODIFY!!! This class was generated by the Terradatum JDBC Code Generator and will be overwritten if regenerated
 * @date 2016-04-30T16:58:56.490
 */
public class NumberTbl extends JdbcArrayList<java.math.BigDecimal> {
  public static final String SQL_TYPE_NAME = "jdbc_test.number_tbl";
  public static final char EDB_ARRAY_DELIMITER = ',';
  private final ArrayList<java.math.BigDecimal> delegate = new ArrayList<>();

  /**
   * Required default constructor.
   */
  @SuppressWarnings("unused")
  public NumberTbl() {}

  @Override
  protected ArrayList<java.math.BigDecimal> delegate() {
    return delegate;
  }

  @Override
  public String getSQLTypeName() {
    return SQL_TYPE_NAME;
  }

  @Override
  public String getBaseTypeName() {
    return "java.math.BigDecimal";
  }

  @Override
  public int getBaseType() {
    return BIGINT;
  }

  @Override
  public char getEdbArrayDelimiter() {
    return EDB_ARRAY_DELIMITER;
  }

  @Override
  public NumberTbl setArray(Array array) throws SQLException, InvocationTargetException,
      NoSuchMethodException, IllegalAccessException, NoSuchFieldException {
    super.setArray(array);
    return this;
  }

  @Override
  public NumberTbl setElements(java.math.BigDecimal[] elements) throws SQLException {
    super.setElements(elements);
    return this;
  }
}