package com.terradatum.jdbc.db.objects.jdbcTest;

import com.terradatum.jdbc.JdbcArrayList;
import com.terradatum.jdbc.StructArrayList;

import java.lang.reflect.InvocationTargetException;
import java.sql.Array;
import java.sql.SQLException;
import java.util.ArrayList;

import static java.sql.Types.*;

/**
 * DO NOT MODIFY!!! This class was generated by the Terradatum JDBC Code Generator and will be overwritten if regenerated
 * @date 2016-05-01T17:05:21.967
 */
public class ParentTbl extends StructArrayList<ParentObj> {
  public static final String SQL_TYPE_NAME = "jdbc_test.parent_tbl";
  public static final char EDB_ARRAY_DELIMITER = ',';
  private final ArrayList<ParentObj> delegate = new ArrayList<>();

  /**
   * Required default constructor.
   */
  @SuppressWarnings("unused")
  public ParentTbl() {}

  @Override
  protected ArrayList<ParentObj> delegate() {
    return delegate;
  }

  @Override
  public String getSQLTypeName() {
    return SQL_TYPE_NAME;
  }

  @Override
  public String getBaseTypeName() {
    return ParentObj.SQL_TYPE_NAME;
  }

  @Override
  public int getBaseType() {
    return STRUCT;
  }

  @Override
  public char getEdbArrayDelimiter() {
    return EDB_ARRAY_DELIMITER;
  }

  @Override
  public ParentTbl setArray(Array array) throws SQLException, InvocationTargetException,
      NoSuchMethodException, IllegalAccessException, NoSuchFieldException {
    super.setArray(array);
    return this;
  }

  @Override
  public ParentTbl setElements(ParentObj[] elements) throws SQLException {
    super.setElements(elements);
    return this;
  }
}