package com.terradatum.jdbc.db.model;

import com.terradatum.jdbc.JdbcArrayList;

import java.math.BigDecimal;
import java.util.ArrayList;

/**
 * DO NOT MODIFY!!! This class was generated by the Terradatum JDBC Code Generator and will be overwritten if regenerated
 * 
 * @date 2016-02-08T15:35:11.699
 */
public class NumberTbl extends JdbcArrayList<java.math.BigDecimal> {
  private final ArrayList<BigDecimal> delegate = new ArrayList<>();
  public static final String SQL_TYPE_NAME = "terradatum.number_tbl";

  /**
   * Required default constructor.
   */
  @SuppressWarnings("unused")
  public NumberTbl() {
  }

  @Override
  protected ArrayList<java.math.BigDecimal> delegate() {
    return delegate;
  }

  @Override
  public String getSQLTypeName() {
    return SQL_TYPE_NAME;
  }
}